# Generated by Django 3.1.5 on 2021-02-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20210208_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(max_length=500),
        ),
    ]
